<a href="https://colab.research.google.com/github/jlpaniagua/FundamentalsAI/blob/master/Semana1IntroduccionPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Primer Prgrama en Python**


In [0]:
print("Hola Mundo")

# **Programas Basicos**

1) Crear dos variables numericas, sumarlas y mostrar el resultado








In [0]:
variable1 = 5
variable2 = 6
 
suma = variable1 + variable2
 
print("La suma de ",variable1,"+",variable2,"=",suma)


2)  Mostrar el precio del IVA de un producto con un valor de 100 y su precio final.



In [0]:
IVA = 0.19
 
precioProducto = 100
 
precioIVA = precioProducto * IVA
 
print("El precio del IVA es", precioIVA, "$")
 
print("El precio final es", (precioIVA+precioProducto) ,"$")


# **Sentencias de Control**
## Senticia if

1) De dos números, saber cual es el mayor.

In [0]:
a = 7
b = 5
 
if( a<b ):
    print("A es menor que B")
else:
    print("B es menor que A")

2) programa que pida al usuario, su edad y determine si es mayor de edad.

In [0]:
edad=int(input("Digite su edad: "))
mayor_edad=18

if edad >= mayor_edad:
    print ("Eres mayor de edad")

3) Realice un programa que pide un número positivo al usuario y almacena la respuesta en la variable "numero". Después comprueba si el número es negativo. Si lo es, el programa avisa que no era eso lo que se había pedido.

In [0]:
numero = int(input("Escriba un número positivo: "))
if numero < 0:
    print("¡Le he dicho que escriba un número positivo!")
print(f"Ha escrito el número {numero}")

## Sentencia if...else

1) programa que pida al usuario, su edad y determine si es mayor de edad o no.

In [0]:
edad = int(input("¿Cuántos años tiene? "))
if edad < 18:
    print("Es usted menor de edad")
else:
    print("Es usted mayor de edad")

2) Realice un programa que determine si el número entero ingresado por el usuario es par o no.


In [0]:
numero=int(input("Ingrese un numero: "))
if (numero%2)==0:
    print("Su numero es par")
else:
    print("Su numero es impar")

## Sentencia if...elif...else

1) Realice un programa que determine si el número entero ingresado por el usuario es positivo, negativo o cero.


In [0]:
numero=int(input("Escriba un numero: "))
if numero>0:
    print("Su numero es positivo")
elif numero<0:
    print("Su numero es negativo")
else:
    print("Su numero es cero")

2) Escriba un programa que pida dos números enteros e indique si son iguales o cual de los dos es mayor.


In [0]:
numero1=float(input("Digite el primer numero"))
numero2=float(input("Digite el segundo numero"))

if numero1 == numero2:
    print("Los numeros son iguales")
elif numero1 >numero2:
    print(numero1, " es mayor que ", numero2)
else:
    print(numero1, " es menor que ", numero2)

## Ciclo for

1) programa que imprima 3 veces la palabra “Hola”


In [18]:
print("inicio")
for numero in [0,1,2,3]:
  print("Hola ", end="")
  print()
print("fin")

inicio
Hola 
Hola 
Hola 
Hola 
fin


2) Escriba un programa que imprima los números impares del 1 al 99


In [0]:
for i in range(1,100):
    if i%2!=0:
        print(i)

## Ciclo while

1) programa que imprima los números del 1 al 3


In [0]:
i=1
while i<=3:
  print(i)
  i+=1
print("Fin")

2) Escriba un programa que pida al usuario un numero positivo una y otra vez hasta que el usuario lo haga correctamente


In [0]:
numero=int(input("Digite un numero positivo:"))

while numero<0:
    print("Ha escrito un numero negativo! Intentelo de nuevo")
    numero=int(input("Digite un numero positivo:"))
print("Gracias")

# **Librerias, Vectores y Matrices**

## Arreglos unidimensionales: Vectores

## Vector de numeros enteros

In [0]:
from numpy import array
a=array([6,1,3,9,8])
print(a)

## Vector de Numeros reales

In [0]:
from numpy import array
a=array([6.0,1,3,9,8])
print(a)

## Operaciones con Vectores

In [0]:
from numpy import array

b = array([6.0, 1, 3, 9, 8])

a = array([6, 1, 3, 9, 8])

# multiplicar por 0.1 todos los elementos
prod=0.1 * a
print(prod)

# restar 9.0 a todos los elementos
resta=a - 9.0
print(resta)


# sumar los dos arreglos elemento a elemento
s=a + b
print(s)

# multiplicar elemento a elemento
m=a * b
print(m)

# restar elemento a elemento
r=a - b
print(r)

#dividir elemento a elemento
d=a/b
print(d)



## Obtener elementos de un vector

### obtener un unico elemento

In [0]:
a=array([6.2, -2.3,3.4,4.7,9.8])
posicion1=a[0]
print(posicion1)

###obtener una seccion de elementos de un vector

In [0]:
a=array([6.2, -2.3,3.4,4.7,9.8])
elementos=a[1:4]
print(elementos)

#Arreglos bidimensionales: Matrices

In [34]:
a=array([[5.1,7.4,3.2,9.9],
         [1.9,6.8,4.1,2.3],
         [2.9,6.4,4.3,1.4]])
print(a)

[[5.1 7.4 3.2 9.9]
 [1.9 6.8 4.1 2.3]
 [2.9 6.4 4.3 1.4]]


## Operaciones con Matrices

###Suma


In [0]:
matrizA=array([[0,0],[0,0]])
matrizB=array([[0,0],[0,0]])


print("Elementos de la Matriz A")
for i in range(0,2):
    for j in range(0,2):
        print("Digite un numero para la Matriz A:")
        matrizA[i,j]=float(input())

print("Elementos de la Matriz B")
for i in range(0,2):
    for j in range(0,2):
        print("Digite un numero para la Matriz B:")
        matrizB[i,j]=float(input())
        
suma=matrizA+matrizB

print("el resultado de la suma de matriz A + matriz B es:",suma)

###Producto

In [0]:
matrizA=array([[0,0],[0,0]])
matrizB=array([[0,0],[0,0]])
producto=array([[0,0],[0,0]])


print("Elementos de la Matriz A")
for i in range(0,2):
    for j in range(0,2):
        print("Digite un numero para la Matriz A:")
        matrizA[i,j]=float(input())
        
print(matrizA)
print("Elementos de la Matriz B")

for i in range(0,2):
    for j in range(0,2):
        print("Digite un numero para la Matriz B:")
        matrizB[i,j]=float(input())
print(matrizB)


for i in range(0,2):
    for j in range(0,2):
        for k in range(0,2):    
            producto[i,j]+=(matrizA[i,k]*matrizB[k,j])

print("el resultado del producto de matriz A x matriz B es:",producto)

#**Forma adecuada de trabajar con Numpy**


In [0]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"


## Numpy tiene muchas funciones para crear arreglos

In [0]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"


## Tipos de Datos de Numpy

In [0]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

## Operaciones matematicas usando las funciones de Numpy

In [0]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


#Operaciones especiales

In [0]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))



In [0]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"
